version: '3.8'

services:
  flask-app:
    build: ./flask-app
    container_name: flask-app
    expose:
      - "5000"

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - flask-app